project:
  type: website

website:
  title: "Max Lisnic"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    header-includes: |
      <link rel="stylesheet" href="https://use.typekit.net/ywh1hax.css">
