project:
  type: website
  output-dir: docs

website:
  title: "Max Lisnic"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.typekit.net/ywh1hax.css">
